FROM python:3.9.5-slim-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY start /start
RUN chmod +x /start

WORKDIR /app
