# Generated by Django 3.2.4 on 2021-06-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(max_length=300),
        ),
    ]
